spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/finsimx_dev
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    root: DEBUG
    com.finsimx: DEBUG
    org.springframework.web: DEBUG
